<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-LucasRezendeUnifill/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Vetor de zeros

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.


In [1]:
import numpy as np

zeros = np.zeros(10)
print(f"Array: {zeros}")
print(f"dtype: {zeros.dtype}")
print(f"shape: {zeros.shape}")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dtype: float64
Shape: (10,)


### 2. Vetor de uns

Crie um array 1D com 10 uns e transforme-o em float64.

In [2]:
import numpy as np

ones = np.ones(10, dtype=np.float64)
print(f"Array: {ones}")
print(f"dtype: {ones.dtype}")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
(10,)


### 3. Sequência 0–9

Crie um array com os inteiros de 0 a 9 (inclusive).

In [3]:
import numpy as np

seq = np.arange(10)
print(f"Array: {seq}")

[0 1 2 3 4 5 6 7 8 9]


### 4. Matriz 3×3 com 0…8

Crie um array 3×3 com os valores 0…8 (reshape).

In [4]:
import numpy as np

matriz = np.arange(9).reshape(3, 3)
print(f"Matriz 3x3:\n{matriz}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 5. Índices não zero

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

In [5]:
import numpy as np

v = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(v)[0]
print(f"Vetor: {v}")
print(f"Índices não-zero: {indices}")

(array([0, 1, 4]),)


### 6. Linspace

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [6]:
import numpy as np

linspace_arr = np.linspace(0, 1, 12)
print(f"12 pontos em [0,1]:\n{linspace_arr}")

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


### 7. Identidade 5×5

Crie uma matriz identidade de ordem 5.

In [7]:
import numpy as np

identidade = np.eye(5)
print(f"Matriz identidade 5x5:\n{identidade}")

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 8. Aleatórios 3×3×3  

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

In [8]:
import numpy as np

rng = np.random.default_rng(42)
aleatorios = rng.random((3, 3, 3))
print(f"Shape: {aleatorios.shape}")
print(f"Primeira camada (3x3):\n{aleatorios[0]}")

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


### 9. Min/Max
Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

In [9]:
import numpy as np

rng = np.random.default_rng(42)
matriz_10x10 = rng.random((10, 10))
print(f"Mínimo: {matriz_10x10.min():.6f}")
print(f"Máximo: {matriz_10x10.max():.6f}")

Matriz (amostra):
 [[0.01329328 0.31791896]
 [0.16341713 0.38891594]]
Valor Mínimo: 0.013293277571827411
Valor Máximo: 0.9995435857971832


### 10. Padronização 1D

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

In [10]:
import numpy as np

x = np.array([1, 2, 3, 4, 5], dtype=float)
x_padronizado = (x - x.mean()) / x.std()
print(f"Original: {x}")
print(f"Padronizado: {x_padronizado}")
print(f"Verificação - Média: {x_padronizado.mean():.10f}, Desvio: {x_padronizado.std():.6f}")

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Média (aprox.): 0.0
Desvio Padrão (aprox.): 0.9999999999999999


### 11. Conversão de tipos

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.

In [11]:
import numpy as np

arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_float32 = arr_int32.astype(np.float32)
arr_int64 = arr_float32.astype(np.int64)
print(f"int32: {arr_int32} (dtype: {arr_int32.dtype})")
print(f"float32: {arr_float32} (dtype: {arr_float32.dtype})")
print(f"int64: {arr_int64} (dtype: {arr_int64.dtype})")

Original (int32): [1 2 3] int32
Para float32: [1. 2. 3.] float32
Para int64: [1 2 3] int64


### 12. Clipping

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

In [12]:
import numpy as np

a = np.array([2, 5, 7, 1, 9])
a_clipped = np.clip(a, 0, 5)
print(f"Original: {a}")
print(f"Clipped [0,5]: {a_clipped}")

[2 5 5 1 5]


### 13. Inversão

Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).


In [13]:
import numpy as np

v = np.arange(10)
v_invertido = np.flip(v)
print(f"Original: {v}")
print(f"Invertido: {v_invertido}")


[9 8 7 6 5 4 3 2 1 0]


### 14. Empilhamento

Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.

In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h_stack = np.hstack([a, b])
v_stack = np.vstack([a, b])
print(f"a: {a}")
print(f"b: {b}")
print(f"Empilhamento horizontal: {h_stack}")
print(f"Empilhamento vertical:\n{v_stack}")

Array a: [1 2 3]
Array b: [4 5 6]

Empilhamento Vertical:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Empilhamento Horizontal:
 [1 2 3 4 5 6]
Shape: (6,)


### 15. Diagonal

Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.

In [15]:
import numpy as np


diagonal = np.diag([5, 5, 5, 5])
print(f"Matriz 4x4:\n{diagonal}")

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


### 16. Somas por eixo
Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.

In [16]:
import numpy as np

A = np.arange(12).reshape(3, 4)
soma_linhas = A.sum(axis=1)
soma_colunas = A.sum(axis=0)
print(f"Matriz A:\n{A}")
print(f"Soma por linhas (axis=1): {soma_linhas}")
print(f"Soma por colunas (axis=0): {soma_colunas}")

Matriz A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Soma por linhas (axis=1): [ 6 22 38]
Soma por colunas (axis=0): [12 15 18 21]


### 17. Frequências inteiras

Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).

In [17]:
import numpy as np

rng = np.random.default_rng(42)
inteiros = rng.integers(0, 10, size=100)
frequencias = np.bincount(inteiros)
print("Frequências:")
for i, freq in enumerate(frequencias):
    print(f"  Valor {i}: {freq} vezes")

Primeiros 20 inteiros gerados: [2 9 2 7 0 8 8 9 0 5 5 5 0 0 6 7 6 5 3 0]

Frequências (para 0, 1, ..., 9):
[13  4  9  9 12 16  9  7 11 10]


### 18. Slicing com passo

Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.

In [18]:
import numpy as np

v = np.arange(20)
selecionado = v[1::3]
print(f"Vetor completo: {v}")
print(f"Cada 3º elemento (início=1): {selecionado}")

Vetor original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Cada 3º elemento a partir do índice 1: [ 1  4  7 10 13 16 19]


### 19. Máscara booleana

Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.

In [19]:
import numpy as np

v = np.arange(20)
mascara = (v % 2 == 0)
pares = v[mascara]
print(f"Vetor: {v}")
print(f"Máscara (pares): {mascara}")
print(f"Números pares filtrados: {pares}")

Vetor original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Máscara (Par?): [ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
Vetor filtrado (só pares): [ 0  2  4  6  8 10 12 14 16 18]


### 20. Lista de listas → array

Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.

In [20]:
import numpy as np

lista = [[1, 2, 3], [4, 5, 6]]
arr = np.array(lista)
print(f"Lista original: {lista}")
print(f"Array:\n{arr}")
print(f"Shape: {arr.shape}")
print(f"dtype: {arr.dtype}")

Array NumPy:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dtype: int64


### 21. Datas básicas

Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).


In [21]:
import numpy as np

datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(f"Datas: {datas}")

['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


### 22. Centralizar colunas
Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.

In [22]:
import numpy as np

A = np.array([[1., 2., 3.], [4., 5., 6.]])
media_colunas = A.mean(axis=0)
A_centralizado = A - media_colunas
print(f"Matriz original:\n{A}")
print(f"Média das colunas: {media_colunas}")
print(f"Matriz centralizada:\n{A_centralizado}")

Matriz Original:
 [[1. 2. 3.]
 [4. 5. 6.]]

Média das colunas: [2.5 3.5 4.5]

Matriz Centralizada:
 [[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]

Nova média das colunas (deve ser ~0):
 [0. 0. 0.]


### 23. Produto elemento-a-elemento vs. escalar

---



Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.

In [23]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
prod_elem = a * b
prod_escalar = np.dot(a, b)
print(f"a: {a}")
print(f"b: {b}")
print(f"Produto elemento-a-elemento (a*b): {prod_elem}")
print(f"Produto escalar (dot): {prod_escalar}")


Array a: [1 2 3]
Array b: [4 5 6]

Produto Elemento-a-Elemento (a * b): [ 4 10 18]
Produto Escalar (np.dot(a, b)): 32


### 24. Troca de colunas

Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).

In [24]:
import numpy as np

A = np.arange(12).reshape(3, 4)
print(f"Matriz original:\n{A}")
A[:, [0, 2]] = A[:, [2, 0]]
print(f"Após trocar colunas 0 e 2:\n{A}")

Matriz Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Matriz com colunas 0 e 2 trocadas:
 [[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


### 25. Flatten vs. ravel

---



Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.

In [25]:
import numpy as np

A = np.arange(6).reshape(2, 3)
print(f"Array original:\n{A}")
flat = A.flatten()
rav = A.ravel()
print(f"flatten(): {flat}")
print(f"ravel(): {rav}")
print("\nModificando ravel()[0] = 999:")
rav[0] = 999
print(f"  ravel() modificado: {rav}")
print(f"  Array original:\n{A}")
print("Conclusão: ravel() retorna view (modifica original), flatten() retorna cópia")

Matriz Original A:
 [[0 1 2]
 [3 4 5]]

--- Testando ravel() ---
A foi modificado? (Sim):
 [[99  1  2]
 [ 3  4  5]]

Matriz A resetada:
 [[0 1 2]
 [3 4 5]]

--- Testando flatten() ---
A foi modificado? (Não):
 [[0 1 2]
 [3 4 5]]
Array 'f' (a cópia):
 [77  1  2  3  4  5]


### 26. Tabuleiro 8×8  
Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).

In [26]:
import numpy as np

tabuleiro = np.zeros((8, 8), dtype=int)
tabuleiro[::2, 1::2] = 1
tabuleiro[1::2, ::2] = 1
print(f"Tabuleiro 8x8:\n{tabuleiro}")

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 27. np.where condicional

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

In [27]:
import numpy as np

x = np.arange(-5, 6)
x_modificado = np.where(x < 0, 0, x)
print(f"Original: {x}")
print(f"Modificado: {x_modificado}")

Vetor Original: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Vetor modificado: [0 0 0 0 0 0 1 2 3 4 5]


### 28. Precisão de média

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).

In [28]:
import numpy as np

rng = np.random.default_rng(42)
floats = rng.random(1_000_000)
media = floats.mean()
erro = abs(media - 0.5)
print(f"Média calculada: {media:.10f}")
print(f"Valor teórico: 0.5000000000")
print(f"Erro absoluto: {erro:.10f}")

print(f"Total de números: {len(dados)}")
print(f"Média calculada: {media_calculada}")
print(f"Valor teórico:   {valor_teorico}")
print(f"Erro absoluto:   {erro_abs}")

Total de números: 1000000
Média calculada: 0.5000264761740889
Valor teórico:   0.5
Erro absoluto:   2.6476174088907456e-05


### 29. Produto cartesiano (broadcasting)
Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).

In [29]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])
somas = a[:, np.newaxis] + b
print(f"a: {a}")
print(f"b: {b}")
print(f"Todas as somas a_i + b_j (broadcasting):\n{somas}")

a (coluna 3x1):
 [[1]
 [2]
 [3]]

b (linha 1x4): [10 20 30 40]

Somas (broadcasting 3x4):
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


### 30. Convolução 1D simples

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).

In [30]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

s = np.array([1, 2, 3, 4, 5])
k = np.array([1, 0, -1])
k_flip = np.flip(k)
windows = sliding_window_view(s, len(k))
conv_result = (windows * k_flip).sum(axis=1)
print(f"Sinal: {s}")
print(f"Kernel: {k}")
print(f"Kernel invertido: {k_flip}")
print(f"Convolução 1D (valid): {conv_result}")

Sinal: [1 2 3 4 5 6]
Kernel: [ 1  0 -1]
Janelas (views):
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
Kernel invertido: [-1  0  1]

Resultado da Convolução 'valid': [2 2 2 2]


### 31. Normalização min–max por coluna

Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.

In [31]:
import numpy as np

rng = np.random.default_rng(42)
A = rng.normal(size=(5, 4))
print(f"Matriz original (5x4):\n{A}")
min_cols = A.min(axis=0)
max_cols = A.max(axis=0)
range_cols = max_cols - min_cols
range_cols[range_cols == 0] = 1
A_norm = (A - min_cols) / range_cols
print(f"\nMatriz normalizada [0,1]:\n{A_norm}")
print(f"Min por coluna: {A_norm.min(axis=0)}")
print(f"Max por coluna: {A_norm.max(axis=0)}")

Matriz Original A:
 [[ 0.30471708 -1.03998411  0.7504512   0.94056472]
 [-1.95103519 -1.30217951  0.1278404  -0.31624259]
 [-0.01680116 -0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934 -0.85929246]
 [ 0.36875078 -0.9588826   0.8784503  -0.04992591]]

Mínimos por coluna: [-1.95103519 -1.30217951  0.1278404  -0.85929246]
Máximos por coluna: [0.36875078 1.12724121 0.87939797 0.94056472]

Matriz Normalizada [0, 1]:
 [[0.97239672 0.10792507 0.82842728 1.        ]
 [0.         0.         0.         0.30171831]
 [0.83379849 0.18487353 1.         0.9095635 ]
 [0.86950517 1.         0.45195332 0.        ]
 [1.         0.14130813 0.99873905 0.44968376]]

Novo Mínimo (deve ser 0): [0. 0. 0. 0.]
Novo Máximo (deve ser 1): [1. 1. 1. 1.]


### 32. Ordenar por coluna

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.


In [32]:
import numpy as np

A = np.array([[3, 9], [1, 4], [2, 5]])
print(f"Matriz original:\n{A}")
indices_ordem = np.argsort(A[:, 1])
A_ordenado = A[indices_ordem]
print(f"Índices de ordenação pela 2ª coluna: {indices_ordem}")
print(f"Matriz ordenada:\n{A_ordenado}")

Matriz Original A:
 [[3 9]
 [1 4]
 [2 5]]

Índices ordenados (da 2ª col): [1 2 0]

Matriz ordenada pela 2ª coluna:
 [[1 4]
 [2 5]
 [3 9]]


### 33. Únicos + contagens + primeira ocorrência
Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.

In [33]:
import numpy as np

x = np.array([3, 1, 2, 3, 2, 3, 1])
unicos, indices, contagens = np.unique(x, return_index=True, return_counts=True)
print(f"Array original: {x}")
print(f"Valores únicos: {unicos}")
print(f"Contagens: {contagens}")
print(f"Primeira ocorrência (índice): {indices}")

Vetor original: [3 1 2 3 2 3 1]

Valores únicos: [1 2 3]
Índice da primeira ocorrência: [1 2 0]
Contagem de cada valor: [2 2 3]


### 34. Matriz de distâncias 2D

Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.

In [34]:
import numpy as np

rng = np.random.default_rng(42)
P = rng.random((5, 2))
diff = P[:, np.newaxis, :] - P[np.newaxis, :, :]
distancias = np.sqrt((diff ** 2).sum(axis=2))
print(f"Pontos (5 pontos 2D):\n{P}")
print(f"\nMatriz de distâncias (5x5):\n{distancias}")

Pontos P (Shape 5x2):
 [[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]
 [0.7611397  0.78606431]
 [0.12811363 0.45038594]]

Matriz de Distâncias Euclidianas (5x5):
 [[0.         0.2719947  0.86613689 0.34742234 0.64594493]
 [0.2719947  0.         0.81348895 0.13177683 0.77110793]
 [0.86613689 0.81348895 0.         0.69337655 0.52633161]
 [0.34742234 0.13177683 0.69337655 0.         0.71652074]
 [0.64594493 0.77110793 0.52633161 0.71652074 0.        ]]


### 35. Covariância e correlação

Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.

In [35]:
import numpy as np

rng = np.random.default_rng(42)
X = rng.normal(size=(1000, 3))
cov_matrix = np.cov(X, rowvar=False)
corr_matrix = np.corrcoef(X, rowvar=False)
print(f"Dimensões de X: {X.shape}")
print(f"\nMatriz de covariância (3x3):\n{cov_matrix}")
print(f"\nMatriz de correlação (3x3):\n{corr_matrix}")

Shape de X (observações, variáveis): (1000, 3)

Matriz de Covariância (3x3):
 [[ 1.02807939  0.003405   -0.03028368]
 [ 0.003405    0.99691425  0.06347086]
 [-0.03028368  0.06347086  1.0227042 ]]

Matriz de Correlação (3x3):
 [[ 1.          0.00336338 -0.02953387]
 [ 0.00336338  1.          0.06285943]
 [-0.02953387  0.06285943  1.        ]]


### 36. One-hot encoding

Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.

In [36]:
import numpy as np

y = np.array([2, 0, 1, 2])
n_classes = y.max() + 1
one_hot = np.eye(n_classes)[y]
print(f"Rótulos: {y}")
print(f"One-hot encoding:\n{one_hot.astype(int)}")

Rótulos (y): [2 0 1 2]

Shape: (4, 3)
Codificação One-Hot:
 [[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


### 37. k-means 2D (NumPy puro)

Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.


In [37]:
import numpy as np
rng = np.random.default_rng(42)
pontos = rng.random((50, 2))
K = 3
centroides = pontos[rng.choice(len(pontos), K, replace=False)]

for iteracao in range(10):
    diff = pontos[:, np.newaxis, :] - centroides[np.newaxis, :, :]
    distancias = np.sqrt((diff ** 2).sum(axis=2))
    clusters = np.argmin(distancias, axis=1)
    for k in range(K):
        if np.sum(clusters == k) > 0:
            centroides[k] = pontos[clusters == k].mean(axis=0)

print(f"Centróides finais após 10 iterações:\n{centroides}")
print(f"Atribuições (primeiros 10 pontos): {clusters[:10]}")
print(f"Distribuição dos clusters: {np.bincount(clusters)}")

Centróides Iniciais:
 [[0.14024909 0.55403614]
 [0.15328432 0.17926831]
 [0.63471832 0.5535794 ]]

Centróides Finais (após 10 iterações):
 [[0.21590466 0.69961248]
 [0.45118606 0.19895016]
 [0.770169   0.67794585]]


### 38. PCA básica (autovetores)

Implemente PCA 2D→1D: centralize `X` (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.


In [38]:
import numpy as np

rng = np.random.default_rng(42)
X = rng.normal(size=(100, 2))
X_centered = X - X.mean(axis=0)
cov = np.cov(X_centered, rowvar=False)
autovalores, autovetores = np.linalg.eig(cov)
idx_max = np.argmax(autovalores)
pc1 = autovetores[:, idx_max]
X_proj = X_centered @ pc1
X_recon = np.outer(X_proj, pc1) + X.mean(axis=0)
print(f"Autovalores: {autovalores}")
print(f"Primeiro autovetor (PC1): {pc1}")
print(f"Shape da projeção: {X_proj.shape}")
print(f"Erro de reconstrução (MSE): {np.mean((X - X_recon)**2):.6f}")

Shape dados X: (100, 2)

Matriz Covariância (2x2):
 [[0.83260985 0.63086441]
 [0.63086441 0.57097203]]

Autovalores: [0.05750568 1.3460762 ]
Autovetores:
 [[ 0.63125074 -0.77557882]
 [-0.77557882 -0.63125074]]

1º Componente Principal (W):
 [[-0.77557882]
 [-0.63125074]]

Dados Projetados (Z) (100x1) (primeiros 5): [-0.48483111 -1.25824298  2.45061252 -0.31634428  0.37907857]

Shape Reconstruído: (100, 2)


\### 39. Convolução 2D (im2col)

Implemente convolução 2D 'valid' de uma imagem `I` por um kernel `K` usando `sliding_window_view` para gerar blocos e multiplicação matricial.

In [39]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
rng = np.random.default_rng(42)
I = rng.random((6, 6))
K = np.array([[1, 0, -1],
              [1, 0, -1],
              [1, 0, -1]])
windows = sliding_window_view(I, K.shape)
windows_flat = windows.reshape(-1, K.size)
K_flat = K.flatten()
conv_result = (windows_flat @ K_flat).reshape(windows.shape[:2])
print(f"Imagem 6x6 (amostra 3x3):\n{I[:3, :3]}")
print(f"\nKernel 3x3:\n{K}")
print(f"\nResultado da convolução 2D (4x4):\n{conv_result}")

Shape Imagem: (5, 5)
Shape Kernel: (3, 3)
Shape das Janelas (Views): (3, 3, 3, 3)
Shape Kernel achatado: (9,)
Shape Janelas achatadas: (9, 9)

Convolução 2D 'valid' (resultado):
 [[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]


### 40. Sistemas lineares e resíduo

Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva `Ax=b` com `np.linalg.solve`. Compute o resíduo relativo `||Ax−b||/||b||` e `cond(A)`.

In [40]:
import numpy as np

rng = np.random.default_rng(42)
A = rng.normal(size=(100, 100))
A = A @ A.T + 10 * np.eye(100)
b = rng.normal(size=100)
x = np.linalg.solve(A, b)
residuo_rel = np.linalg.norm(A @ x - b) / np.linalg.norm(b)
cond = np.linalg.cond(A)
print(f"Dimensões de A: {A.shape}")
print(f"Dimensões de b: {b.shape}")
print(f"Dimensões de x: {x.shape}")
print(f"Resíduo relativo: {residuo_rel:.2e}")
print(f"Número de condição de A: {cond:.2e}")
print("(Resíduo baixo indica solução precisa)")

Sistema N=100
Número de Condição cond(A): 1.553882670511607
Norma do Resíduo ||Ax - b||: 1.7666674615290067e-15
Norma de b ||b||: 5.938917820663178
Resíduo Relativo ||Ax - b|| / ||b||: 2.974729597002117e-16


### 41. Regressão linear (OLS) com NumPy

Dado `X` (N×d) e `y`, calcule os coeficientes OLS usando `np.linalg.lstsq` e avalie RMSE no treino.

In [41]:
import numpy as np

rng = np.random.default_rng(seed=42)

N, d = 100, 3
X = rng.random(size=(N, d))

beta_verdadeiro = np.array([5.0, -2.0, 1.5])
intercepto_verdadeiro = 3.0
ruido = rng.normal(scale=0.1, size=N)

y = intercepto_verdadeiro + (X @ beta_verdadeiro) + ruido

X_b = np.hstack([np.ones((N, 1)), X])
print(f"Shape X original: {X.shape}, Shape y: {y.shape}")
print(f"Shape X com intercepto (X_b): {X_b.shape}")
coefs, _, _, _ = np.linalg.lstsq(X_b, y, rcond=None)

intercepto_calc = coefs[0]
betas_calc = coefs[1:]
print("\n--- Resultados OLS ---")
print(f"Intercepto Verdadeiro (B0): {intercepto_verdadeiro:.4f}")
print(f"Intercepto Calculado: {intercepto_calc:.4f}")
print(f"\nBetas Verdadeiros (B1, B2, B3): {beta_verdadeiro}")
print(f"Betas Calculados: {betas_calc}")

y_pred = X_b @ coefs
mse = np.mean((y - y_pred)**2)
rmse = np.sqrt(mse)

print(f"\nRMSE (no treino): {rmse:.5f}")

Shape X original: (100, 3), Shape y: (100,)
Shape X com intercepto (X_b): (100, 4)

--- Resultados OLS ---
Intercepto Verdadeiro (B0): 3.0000
Intercepto Calculado: 3.0109

Betas Verdadeiros (B1, B2, B3): [ 5.  -2.   1.5]
Betas Calculados: [ 5.01368109 -1.98126003  1.46262967]

RMSE (no treino): 0.10147


### 42. Rolling window 2D com strides

Usando `sliding_window_view`, compute a média local 3×3 de uma imagem 2D sem laços explícitos.

In [42]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

rng = np.random.default_rng(42)
imagem = rng.random((10, 10))
windows = sliding_window_view(imagem, (3, 3))
medias = windows.mean(axis=(2, 3))
print(f"Imagem original (10x10), amostra 4x4:\n{imagem[:4, :4]}")
print(f"\nMédias locais 3x3 (8x8):\n{medias}")
print(f"Shape das médias: {medias.shape}")

Imagem Original (6x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Shape das Views (Janelas): (4, 4, 3, 3)

Matriz de Média Local 3x3 (4x4):
 [[ 7.  8.  9. 10.]
 [13. 14. 15. 16.]
 [19. 20. 21. 22.]
 [25. 26. 27. 28.]]
